#ifndef OPERATION_H
#define OPERATION_H

typedef enum BinaryOperation
{
    BINARYOPERATION_ADDITION,
    BINARYOPERATION_SUBTRACTION,
    BINARYOPERATION_MULTIPLICATION,
    BINARYOPERATION_DIVISION,
    BINARYOPERATION_MODULO,

    BINARYOPERATION_EQUALTO,
    BINARYOPERATION_NOTEQUALTO,
    BINARYOPERATION_LESSTHAN,
    BINARYOPERATION_LESSTHANOREQUALTO,
    BINARYOPERATION_GREATERTHAN,
    BINARYOPERATION_GREATERTHANOREQUALTO,

    BINARYOPERATION_AND,
    BINARYOPERATION_OR,
} BinaryOperation;

typedef enum UnaryOperation
{
    UNARYOPERATION_NOT,
    UNARYOPERATION_NEGATION,
    UNARYOPERATION_DEREFERENCE,
} UnaryOperation;

#endif
